name: Build Mandelbrot .exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup GCC
      run: |
        choco install mingw

    - name: Compile mandelbrot.c
      run: |
        gcc mandelbrot.c -o mandelbrot.exe -lm

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: mandelbrot-exe
        path: mandelbrot.exe
